// <auto-generated />
using System;
using HMI_CoolingEquipment.Communication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HMI_CoolingEquipment.Migrations
{
    [DbContext(typeof(DB_Context))]
    [Migration("20230725032747_v1.2.0.0")]
    partial class v1200
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HMI_CoolingEquipment.Models.JOBDETAILS", b =>
                {
                    b.Property<string>("JobID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CarrierID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CarrierStatus")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LoadingTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("PortLocation")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UnloadingTime")
                        .HasColumnType("DateTime");

                    b.HasKey("JobID", "CarrierID");

                    b.ToTable("JOBDETAILS");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.SETTINGS", b =>
                {
                    b.Property<string>("Items")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Items");

                    b.ToTable("SETTINGS");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.SETUPJOB", b =>
                {
                    b.Property<string>("JobID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("CT_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("CT_START")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("DateTime");

                    b.Property<string>("CoolingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("DateTime");

                    b.Property<string>("JobStatus")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LD_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("LD_START")
                        .HasColumnType("DateTime");

                    b.Property<string>("LoadingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ST_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("ST_START")
                        .HasColumnType("DateTime");

                    b.Property<string>("StagingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("JobID");

                    b.ToTable("SETUPJOB");
                });
#pragma warning restore 612, 618
        }
    }
}
