// <auto-generated />
using System;
using HMI_CoolingEquipment.Communication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HMI_CoolingEquipment.Migrations
{
    [DbContext(typeof(DB_Context))]
    [Migration("20230814090313_v2.0.0.0")]
    partial class v2000
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HMI_CoolingEquipment.Models.BIN", b =>
                {
                    b.Property<string>("BinID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("BinColumn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("BinError")
                        .HasColumnType("bit");

                    b.Property<string>("BinIPAddress")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("BinNodeAddress")
                        .HasColumnType("int");

                    b.Property<bool>("BinNodeConnectionStatus")
                        .HasColumnType("bit");

                    b.Property<string>("BinRack")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("BinReadyToLoad")
                        .HasColumnType("bit");

                    b.Property<bool>("BinReadyToUnload")
                        .HasColumnType("bit");

                    b.Property<string>("BinRow")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("BinState")
                        .HasColumnType("int");

                    b.Property<string>("BinType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LoadDetails")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PreAssignLoad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("BinID");

                    b.ToTable("BIN");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.JOBDETAILS", b =>
                {
                    b.Property<string>("JobID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CarrierID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CarrierStatus")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LoadingTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("PortLocation")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UnloadingTime")
                        .HasColumnType("DateTime");

                    b.HasKey("JobID", "CarrierID");

                    b.ToTable("JOBDETAILS");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.SETTINGS", b =>
                {
                    b.Property<string>("Items")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Items");

                    b.ToTable("SETTINGS");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.SETUPJOB", b =>
                {
                    b.Property<string>("JobID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("CT_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("CT_START")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("DateTime");

                    b.Property<string>("CoolingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("DateTime");

                    b.Property<string>("JobStatus")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LD_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("LD_START")
                        .HasColumnType("DateTime");

                    b.Property<string>("LoadingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ST_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("ST_START")
                        .HasColumnType("DateTime");

                    b.Property<string>("StagingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("JobID");

                    b.ToTable("SETUPJOB");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.USERACCOUNT", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("DateTime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("UserName");

                    b.ToTable("USERACCOUNT");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.USERGROUPACCESS", b =>
                {
                    b.Property<string>("UserGroup")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("EditUserAccountList")
                        .HasColumnType("bit");

                    b.Property<bool>("EditUserGroupAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("LoadingPageAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("LotStatusPageAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("SecsGemPageAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("SettingPageAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("UnloadingPageAccess")
                        .HasColumnType("bit");

                    b.HasKey("UserGroup");

                    b.ToTable("USERGROUPACCESS");
                });
#pragma warning restore 612, 618
        }
    }
}
