// <auto-generated />
using System;
using HMI_CoolingEquipment.Communication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HMI_CoolingEquipment.Migrations
{
    [DbContext(typeof(DB_Context))]
    [Migration("20240226102102_AddedNewColumn")]
    partial class AddedNewColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HMI_CoolingEquipment.Models.ALARMCURRENT", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlarmAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AlarmCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("AlarmDateTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("AlarmMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlarmModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AlarmType")
                        .HasColumnType("int")
                        .HasMaxLength(50);

                    b.HasKey("No");

                    b.ToTable("ALARMCURRENT");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.ALARMDEFINITION", b =>
                {
                    b.Property<int>("AlarmType")
                        .HasColumnType("int")
                        .HasMaxLength(50);

                    b.Property<int>("AlarmCode")
                        .HasColumnType("int");

                    b.Property<string>("AlarmAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlarmMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlarmModule")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlarmType", "AlarmCode");

                    b.ToTable("ALARMDEFINITION");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.ALARMHISTORY", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlarmAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AlarmClearedDateTime")
                        .HasColumnType("DateTime");

                    b.Property<int>("AlarmCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("AlarmDateTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("AlarmMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlarmModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AlarmType")
                        .HasColumnType("int")
                        .HasMaxLength(50);

                    b.HasKey("No");

                    b.ToTable("ALARMHISTORY");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.EVENTLOG", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarrierID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("EventMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventPage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadPortID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LotID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("No");

                    b.ToTable("EVENTLOG");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.JOBDETAILS", b =>
                {
                    b.Property<string>("JobID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LotNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CarrierID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("CarrierStatus")
                        .HasColumnType("int");

                    b.Property<string>("LoadBy")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LoadingTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("PortLocation")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UnloadBy")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UnloadingTime")
                        .HasColumnType("DateTime");

                    b.HasKey("JobID", "LotNo", "CarrierID");

                    b.ToTable("JOBDETAILS");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.JOBDETAILSHISTORY", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarrierID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LoadBy")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LoadingTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("PortLocation")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("SETUPJOBHISTORYNo")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UnloadBy")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UnloadingTime")
                        .HasColumnType("DateTime");

                    b.HasKey("No");

                    b.HasIndex("SETUPJOBHISTORYNo");

                    b.ToTable("JOBDETAILSHISTORY");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.LOADPORT", b =>
                {
                    b.Property<string>("LoadPortID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LoadPortCarrierLoad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LoadPortColumn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("LoadPortError")
                        .HasColumnType("bit");

                    b.Property<string>("LoadPortIPAddress")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("LoadPortIsEnable")
                        .HasColumnType("bit");

                    b.Property<int?>("LoadPortNodeAddress")
                        .HasColumnType("int");

                    b.Property<bool>("LoadPortNodeConnectionStatus")
                        .HasColumnType("bit");

                    b.Property<string>("LoadPortPriority")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LoadPortRack")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LoadPortRow")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("LoadPortState")
                        .HasColumnType("int");

                    b.Property<string>("LoadPortType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PreAssignLoad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("LoadPortID");

                    b.ToTable("LOADPORT");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.LOADPORTCONFIGURATION", b =>
                {
                    b.Property<string>("LoadPortStatusKey")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("LoadPortLEDColour")
                        .HasColumnType("int");

                    b.Property<int>("LoadPortLEDState")
                        .HasColumnType("int");

                    b.Property<int>("LoadPortStatusState")
                        .HasColumnType("int");

                    b.HasKey("LoadPortStatusKey");

                    b.ToTable("LOADPORTCONFIGURATION");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.SETTINGS", b =>
                {
                    b.Property<string>("Items")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Page")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Items", "Page");

                    b.ToTable("SETTINGS");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.SETUPJOB", b =>
                {
                    b.Property<string>("JobID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LotNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("CT_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("CT_START")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("DateTime");

                    b.Property<string>("CoolingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("DateTime");

                    b.Property<bool>("IsJobError")
                        .HasColumnType("bit");

                    b.Property<int?>("JobStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LD_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("LD_EXPECTED_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("LD_START")
                        .HasColumnType("DateTime");

                    b.Property<int>("NoOfCarrier")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ST_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("ST_EXPECTED_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("ST_START")
                        .HasColumnType("DateTime");

                    b.Property<string>("StagingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("JobID", "LotNo");

                    b.ToTable("SETUPJOB");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.SETUPJOBHISTORY", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CT_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("CT_START")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("DateTime");

                    b.Property<string>("JobID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LD_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("LD_EXPECTED_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("LD_START")
                        .HasColumnType("DateTime");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("NoOfCarrier")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ST_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("ST_EXPECTED_END")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("ST_START")
                        .HasColumnType("DateTime");

                    b.HasKey("No");

                    b.ToTable("SETUPJOBHISTORY");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.USERACCOUNT", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("DateTime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("UserName");

                    b.ToTable("USERACCOUNT");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.USERGROUPACCESS", b =>
                {
                    b.Property<string>("UserGroup")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("EditUserAccountList")
                        .HasColumnType("bit");

                    b.Property<bool>("EditUserGroupAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("LoadingPageAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("LotStatusPageAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("PTLPageAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("SecsGemPageAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("SettingPageAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("UnloadingPageAccess")
                        .HasColumnType("bit");

                    b.HasKey("UserGroup");

                    b.ToTable("USERGROUPACCESS");
                });

            modelBuilder.Entity("HMI_CoolingEquipment.Models.JOBDETAILSHISTORY", b =>
                {
                    b.HasOne("HMI_CoolingEquipment.Models.SETUPJOBHISTORY", null)
                        .WithMany("JobDetails")
                        .HasForeignKey("SETUPJOBHISTORYNo");
                });
#pragma warning restore 612, 618
        }
    }
}
